### ISSUE TITLE
Alternative negative binomial parameterization?

### ISSUE THREAD

**Issue by sdwfrost** [theogf/AugmentedGaussianProcesses.jl#64]
Hi @theogf! I'd like to fit some overdispersed count data, for which I'd like to use a negative binomial distribution, and infer the overdispersion parameter (ideally also putting a GP on that as well but that's another issue). I saw that in your implementation of the negative binomial, you have `r` as an `Int` rather than allowing it to be a `Float`. Is there any reason to restrict `r` in this way?

**Comment by theogf** [comment]
Hi @sdwfrost, having `r` as an `Int` definitely helps for computing the normalization constant, but other than that there is no constraint. Having another `GP` as a source for `r` would be extremely complex I think... Since `r` appears in the binomial coefficient my wild guess would be that gradients would be quite unstable.
Nonetheless I can make a PR to change that, I am in the AISTATS deadline rush right now but I will take care of it afterwards (with a partial refactoring of the package actually :P )

**Comment by theogf** [comment]
Hi @sdwfrost, so I had a look if `r` could be unrestricted to Integers and the problem would come from this line : https://github.com/theogf/AugmentedGaussianProcesses.jl/blob/089025c850fb4e0c3ff29cbf0a5ede339d4894e0/src/likelihood/negativebinomial.jl#L131

The binomial can only take integers, if you have a an alternative solution, I would be happy to add it!

**Comment by sdwfrost** [comment]
You can use Gamma functions instead of binomial coefficients, as described [here](https://mathworld.wolfram.com/BinomialCoefficient.html). Ideally, I'd like a parameterization along the same lines as the [alternative parameterization](https://mc-stan.org/docs/2_24/functions-reference/nbalt.html) in Stan.

**Comment by theogf** [comment]
Ok so I created #68, I did not copy the Stan parametrization as it would become too heavy, but it is now possible to use Real numbers for `r`. I also added a small example for it in `docs/examples`
